version: '3.8'
services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - 1935:1935
      - 8080:8080
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./player:/var/www/html
    restart: always
